apiVersion: v1
kind: Service
metadata:
  name: grpc-file-client
spec:
  selector:
    app: grpc-file-client
  ports:
    - protocol: TCP
      port: 50052  # Different port if you expose the client
      targetPort: 50052

