# Use an official Golang runtime as the base image
FROM golang:1.24-alpine

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the Go client source code to the container
COPY . .

WORKDIR /app/client

# Build the Go client binary
RUN go build -o grpc-client ./ClientService.go


# Command to run the client binary
CMD ["./grpc-client"]

