apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-file-server
  template:
    metadata:
      labels:
        app: grpc-file-server
    spec:
      containers:
        - name: grpc-file-server
          image: ssahoo1d/grpc-file-server:latest
          ports:
            - containerPort: 50053
      imagePullSecrets:
        - name: my-registry-secret

